version: '3.7'
services:
    postgres:
      image: postgres:9.6
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=admin
      logging:
        options:
            max-size: 10m
            max-file: "3"
    worker:
      depends_on:
        - postgres
      build:
        dockerfile: Dockerfile
        context: .
      command: tail -F anything
      logging:
        options:
          max-size: 10m
          max-file: "3"
